#!/usr/bin/env python3
"""Self-host the two typefaces the site actually uses.

Every page linked a stylesheet from fonts.googleapis.com requesting **six**
families: Alex Brush, Cormorant Garamond (eight weights plus italics), Dancing
Script, Great Vibes, Plus Jakarta Sans and Satisfy.

The stylesheet only ever resolves to two of them. `--font-script` lists Alex
Brush, Satisfy and Great Vibes purely as fallbacks behind Dancing Script, which
always loads, so none of the three can ever render — and Cormorant Garamond is
not referenced anywhere at all. `--font-serif` is also byte-for-byte identical
to `--font-sans`, so the "serif" token has never produced a serif.

Self-hosting is worth more than the bytes: the old path was two sequential
round trips to two third-party hosts (googleapis for the CSS, then gstatic for
the files) before any text could paint in its real face, and every visitor's IP
was handed to Google on the way. Same-origin files start downloading with the
rest of the page.

Latin and latin-ext subsets only. The site's copy is English; the ext subset is
cheap insurance for accented names in a testimonial.

Both families are licensed under the SIL Open Font License, which permits
redistribution — see fonts/OFL.txt.

Run:  python3 tools/build_fonts.py
"""
import io
import os
import re
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..')
FONTS = os.path.join(ROOT, 'fonts')

UA = ('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/120.0 Safari/537.36')

# Variable ranges covering exactly the weights the stylesheet asks for.
FAMILIES = {
    'Plus Jakarta Sans': ('plus-jakarta-sans', 'wght@400..800'),
    'Dancing Script': ('dancing-script', 'wght@500..700'),
}
WANT_SUBSETS = ('latin', 'latin-ext')


def fetch(url):
    req = urllib.request.Request(url, headers={'User-Agent': UA})
    return urllib.request.urlopen(req).read()


def main():
    os.makedirs(FONTS, exist_ok=True)
    blocks = []

    for family, (slug, axis) in FAMILIES.items():
        css = fetch('https://fonts.googleapis.com/css2?family='
                    + family.replace(' ', '+') + ':' + axis
                    + '&display=swap').decode('utf-8')

        # each @font-face is preceded by a /* subset */ comment
        for subset, face in re.findall(r'/\* (\S+) \*/\s*(@font-face \{.*?\})', css, re.S):
            if subset not in WANT_SUBSETS:
                continue
            url = re.search(r'url\((\S+?)\)', face).group(1)
            rng = re.search(r'unicode-range: ([^;]+);', face).group(1)
            weight = re.search(r'font-weight: ([^;]+);', face).group(1)

            name = f'{slug}-{subset}.woff2'
            io.open(os.path.join(FONTS, name), 'wb').write(fetch(url))
            kb = os.path.getsize(os.path.join(FONTS, name)) / 1024
            print(f'  fonts/{name}  {kb:.0f} KB')

            blocks.append(
                f'@font-face {{\n'
                f"  font-family: '{family}';\n"
                f'  font-style: normal;\n'
                f'  font-weight: {weight};\n'
                f'  font-display: swap;\n'
                f"  src: url('../fonts/{name}') format('woff2');\n"
                f'  unicode-range: {rng};\n'
                f'}}')

    header = (
        '/* Self-hosted typefaces — generated by tools/build_fonts.py.\n'
        '   Replaces a render-blocking stylesheet from fonts.googleapis.com that\n'
        '   requested six families where only these two ever render. Both are SIL\n'
        '   Open Font License; see fonts/OFL.txt. */\n')
    io.open(os.path.join(ROOT, 'css', 'fonts.css'), 'w', encoding='utf-8').write(
        header + '\n' + '\n\n'.join(blocks) + '\n')
    print(f'\n  css/fonts.css  ({len(blocks)} faces)')


if __name__ == '__main__':
    print('Self-hosting fonts...')
    main()
