#!/usr/bin/env python3
"""Generate the .pico icon CSS that replaces the site's OS emoji.

Emoji render as flat cartoon glyphs supplied by the operating system, which is
what made them stand out against the photoreal artwork elsewhere on the page.

Two icons have a genuine photographic source already in the project and are cut
out by tools/build_icons.py (the crystal orb and the iris). The rest have no
photographic source and no image generation was available, so they are drawn
here as shaded vector objects — radial gradients, a specular highlight and a
grounded shadow — in the site palette, rather than left as OS emoji.

Writes into css/style.css between the PICO markers, so it is re-runnable.

Run:  python3 tools/build_icon_css.py
"""
import os
import re
from urllib.parse import quote

HERE = os.path.dirname(os.path.abspath(__file__))
CSS = os.path.join(HERE, '..', 'css', 'style.css')

START = '/* ===== PICO ICONS: GENERATED by tools/build_icon_css.py — do not edit ===== */'
END = '/* ===== END PICO ICONS ===== */'

VIOLET, TEAL, GOLD = '#9D4EDD', '#00E5D4', '#FFD700'


def defs(*grads):
    return '<defs>' + ''.join(grads) + '</defs>'


def rad(gid, inner, outer, cx='35%', cy='28%', r='72%'):
    return (f'<radialGradient id="{gid}" cx="{cx}" cy="{cy}" r="{r}">'
            f'<stop offset="0%" stop-color="{inner}"/>'
            f'<stop offset="100%" stop-color="{outer}"/></radialGradient>')


def lin(gid, a, b, x2='0', y2='1'):
    return (f'<linearGradient id="{gid}" x1="0" y1="0" x2="{x2}" y2="{y2}">'
            f'<stop offset="0%" stop-color="{a}"/>'
            f'<stop offset="100%" stop-color="{b}"/></linearGradient>')


GLOSS = ('<ellipse cx="21" cy="17" rx="9" ry="5.5" fill="%s" opacity=".55" '
         'transform="rotate(-24 21 17)"/>')

ICONS = {}

# ── bell ────────────────────────────────────────────────────────────────────
ICONS['bell'] = (
    defs(lin('bg', '#FFE87A', '#D9A400'), lin('bs', '#FFF6C9', '#F2C230')) +
    '<path d="M32 7c-1.9 0-3.4 1.5-3.4 3.4v1.3C22 13.2 17.6 19 17.6 25.9v11.4l-3.9 6.4c-.9 1.5.2 3.4 2 3.4h36.6c1.8 0 2.9-1.9 2-3.4l-3.9-6.4V25.9C50.4 19 46 13.2 39.4 11.7v-1.3C39.4 8.5 37.9 7 36 7z" '
    'fill="url(%23bg)" stroke="%23A97A00" stroke-width="1.4" stroke-linejoin="round"/>'
    '<path d="M25 22c1.6-4.2 5.2-7 9.4-7.6" fill="none" stroke="url(%23bs)" stroke-width="3" stroke-linecap="round" opacity=".85"/>'
    '<path d="M27 50.5a7 7 0 0 0 14 0z" fill="url(%23bg)" stroke="%23A97A00" stroke-width="1.4" stroke-linejoin="round"/>'
    '<ellipse cx="34" cy="56" rx="12" ry="3" fill="%23000" opacity=".18"/>'
)

ICONS['bell-off'] = ICONS['bell'] + (
    '<path d="M12 10 54 52" stroke="%23FFFFFF" stroke-width="7" stroke-linecap="round" opacity=".95"/>'
    '<path d="M12 10 54 52" stroke="%23C0392B" stroke-width="4.2" stroke-linecap="round"/>'
)

# ── shopping bag ────────────────────────────────────────────────────────────
ICONS['bag'] = (
    defs(lin('bgv', '#C77DFF', '#6A2CA0'), lin('bgl', '#FFFFFF', '#E3CBFF')) +
    '<path d="M23 20v-3a11 11 0 0 1 22 0v3" fill="none" stroke="url(%23bgl)" stroke-width="4" stroke-linecap="round"/>'
    '<path d="M14 20h40l-3.6 33.4a4 4 0 0 1-4 3.6H21.6a4 4 0 0 1-4-3.6z" '
    'fill="url(%23bgv)" stroke="%234B1B7A" stroke-width="1.6" stroke-linejoin="round"/>'
    + (GLOSS % '%23FFFFFF') +
    '<ellipse cx="34" cy="59" rx="15" ry="3" fill="%23000" opacity=".2"/>'
)

# ── sparkle ─────────────────────────────────────────────────────────────────
ICONS['sparkle'] = (
    defs(rad('sg', '#FFFFFF', '#00E5D4', '50%', '50%', '58%')) +
    '<circle cx="34" cy="32" r="21" fill="url(%23sg)" opacity=".33"/>'
    '<path d="M34 6c2.6 12.4 8.6 20 21 22.6-12.4 2.6-18.4 9.6-21 22-2.6-12.4-8.6-19.4-21-22 12.4-2.6 18.4-10.2 21-22.6z" '
    'fill="%23FFFFFF"/>'
    '<path d="M34 12c2 9.4 6.4 15 15.6 17-9.2 2-13.6 7.2-15.6 16.6-2-9.4-6.4-14.6-15.6-16.6 9.2-2 13.6-7.6 15.6-17z" '
    'fill="%2300FFC8" opacity=".8"/>'
    '<circle cx="53" cy="12" r="3.4" fill="%23FFD700"/>'
    '<circle cx="14" cy="49" r="2.4" fill="%23FFD700" opacity=".85"/>'
)

# ── leaf ────────────────────────────────────────────────────────────────────
ICONS['leaf'] = (
    defs(lin('lg', '#7BFFB2', '#128F5A', '1', '1')) +
    '<path d="M53 8C29 8 12 21 12 40c0 6 2 11 5 15C22 34 33 24 48 20 34 27 25 38 22 57c4 2 9 3 14 3 17 0 22-19 22-33 0-8-1-14-5-19z" '
    'fill="url(%23lg)" stroke="%230C5C3B" stroke-width="1.5" stroke-linejoin="round"/>'
    '<path d="M17 55C24 36 33 26 48 20" fill="none" stroke="%23D8FFE9" stroke-width="2.4" stroke-linecap="round" opacity=".7"/>'
)

# ── love letter ─────────────────────────────────────────────────────────────
ICONS['letter'] = (
    defs(lin('eg', '#FFFDF6', '#E4D6C2'), rad('sealg', '#FF8FB1', '#B0165A', '38%', '32%', '70%')) +
    '<rect x="8" y="16" width="52" height="36" rx="5" fill="url(%23eg)" stroke="%23A78B68" stroke-width="1.6"/>'
    '<path d="M8.5 19 34 38 59.5 19" fill="none" stroke="%23A78B68" stroke-width="2.2" stroke-linejoin="round"/>'
    '<circle cx="34" cy="41" r="9" fill="url(%23sealg)" stroke="%237E0E3E" stroke-width="1.2"/>'
    '<path d="M34 45c-3-2.2-5-4-5-6a2.6 2.6 0 0 1 5-1 2.6 2.6 0 0 1 5 1c0 2-2 3.8-5 6z" fill="%23FFD9E4" opacity=".9"/>'
    '<ellipse cx="34" cy="56" rx="18" ry="2.6" fill="%23000" opacity=".16"/>'
)

# ── radiant palm (reiki) ────────────────────────────────────────────────────
ICONS['hand'] = (
    defs(rad('hg', '#FFE3CB', '#C98E63', '38%', '26%', '78%'),
         rad('glow', '#FFFFFF', '#00E5D4', '50%', '50%', '60%')) +
    '<circle cx="34" cy="30" r="19" fill="url(%23glow)" opacity=".45"/>'
    '<path d="M22 30V15a4 4 0 0 1 8 0v12V11a4 4 0 0 1 8 0v16V14a4 4 0 0 1 8 0v18l3-7a3.6 3.6 0 0 1 6.4 3L48 48c-2.6 6-7 9-14 9-8.4 0-14-5.6-14-14V22a4 4 0 0 1 8 0z" '
    'fill="url(%23hg)" stroke="%238A5A38" stroke-width="1.5" stroke-linejoin="round"/>'
    '<circle cx="33" cy="38" r="5" fill="%2300FFC8" opacity=".75"/>'
)

# ── moon ────────────────────────────────────────────────────────────────────
ICONS['moon'] = (
    defs(rad('mg', '#FFF6D0', '#E0B23C', '36%', '30%', '75%')) +
    '<path d="M41 6a26 26 0 1 0 17 46A30 30 0 0 1 41 6z" fill="url(%23mg)" stroke="%23A97A00" stroke-width="1.4"/>'
    '<circle cx="26" cy="24" r="3.2" fill="%23D9A63C" opacity=".5"/>'
    '<circle cx="21" cy="38" r="2.2" fill="%23D9A63C" opacity=".45"/>'
)

# ── candle ──────────────────────────────────────────────────────────────────
ICONS['candle'] = (
    defs(lin('cw', '#FFFBF0', '#DCCBAA'), rad('fl', '#FFF7C2', '#FF8A00', '50%', '68%', '70%')) +
    '<rect x="24" y="24" width="20" height="33" rx="4" fill="url(%23cw)" stroke="%23A78B68" stroke-width="1.5"/>'
    '<path d="M34 6c5 6 8 10 8 14a8 8 0 0 1-16 0c0-4 3-8 8-14z" fill="url(%23fl)"/>'
    '<path d="M34 12c2.4 3.2 3.8 5.4 3.8 7.4a3.8 3.8 0 0 1-7.6 0c0-2 1.4-4.2 3.8-7.4z" fill="%23FFF9DC" opacity=".9"/>'
    '<ellipse cx="34" cy="59" rx="14" ry="2.6" fill="%23000" opacity=".18"/>'
)


# ── dove (redrawn: the first pass read as a blob rather than a bird) ────────
ICONS['dove'] = (
    defs(lin('dg', '#FFFFFF', '#C3D6F7', '.35', '1'), lin('dw', '#FFFFFF', '#DBE7FF', '.6', '1')) +
    # tail fan
    '<path d="M25 40C17 40 10 37 4.5 31.5c4.6 7 4.6 13.4 1.5 18.5 6.4-1.8 11.6-4.2 16-7.4z" '
    'fill="url(%23dg)" stroke="%237E93BF" stroke-width="1.2" stroke-linejoin="round"/>'
    '<path d="M8.5 34.5C11 39 11.6 43.4 10 47.6" fill="none" stroke="%23A9BCE0" stroke-width="1.1" stroke-linecap="round"/>'
    '<path d="M15 38C16.8 41 17.2 43.8 16.2 46.4" fill="none" stroke="%23A9BCE0" stroke-width="1.1" stroke-linecap="round"/>'
    # head + body as one silhouette so there is no seam between them
    '<path d="M50.6 10.6a7.8 7.8 0 0 1 6.1 12.7c1.5 5.7.4 12-3.4 17.1C46.9 49.2 35.4 53 24.4 51.5c-3.4-.5-5.1-2.5-4.7-5.7 1-8.2 5-15.4 11.4-20 3.7-2.6 7.6-4.2 11.4-4.7a7.8 7.8 0 0 1 8.1-10.5z" '
    'fill="url(%23dg)" stroke="%237E93BF" stroke-width="1.4" stroke-linejoin="round"/>'
    # swept wing
    '<path d="M46 28C42 36 35 43.5 25.5 47c5.5-7 10-14 12.5-20 3-1.5 6.5-1.2 8 1z" '
    'fill="url(%23dw)" stroke="%238FA5CE" stroke-width="1.2" stroke-linejoin="round"/>'
    '<path d="M41.5 31.5C37.6 36.6 33.4 41 28.6 44.6" fill="none" stroke="%23A9BCE0" stroke-width="1" stroke-linecap="round"/>'
    '<path d="M44 34.6C40.6 39 36.8 42.6 32.4 45.6" fill="none" stroke="%23A9BCE0" stroke-width="1" stroke-linecap="round"/>'
    # eye + beak
    '<circle cx="52" cy="17.4" r="1.8" fill="%231F2E63"/>'
    '<path d="M57.4 19.4 65 21.4l-7.4 2.8z" fill="%23F2B441" stroke="%23C4880F" stroke-width=".8" stroke-linejoin="round"/>'
    '<ellipse cx="34" cy="57" rx="14" ry="2.4" fill="%23000" opacity=".16"/>'
)

# ── map pin ─────────────────────────────────────────────────────────────────
ICONS['pin'] = (
    defs(rad('png', '#E0AAFF', '#5E2391', '36%', '26%', '76%')) +
    '<ellipse cx="34" cy="57" rx="8.5" ry="2.8" fill="%23000" opacity=".22"/>'
    '<path d="M34 5c-9.4 0-17 7.6-17 17 0 12.2 14.2 27.8 15.4 29.2a2.1 2.1 0 0 0 3.2 0C36.8 49.8 51 34.2 51 22c0-9.4-7.6-17-17-17z" '
    'fill="url(%23png)" stroke="%233D1568" stroke-width="1.5" stroke-linejoin="round"/>'
    '<circle cx="34" cy="21" r="6.4" fill="%23FFF3D0" stroke="%23A97A00" stroke-width="1.2"/>'
    '<ellipse cx="27" cy="14" rx="5" ry="3" fill="%23FFFFFF" opacity=".45" transform="rotate(-28 27 14)"/>'
)

# ── magnifier ───────────────────────────────────────────────────────────────
ICONS['search'] = (
    defs(rad('sgl', '#F2FFFD', '#7FD9D2', '34%', '26%', '80%'), lin('shd', '#C77DFF', '#5E2391')) +
    '<path d="M41 41 56 56" stroke="%233D1568" stroke-width="9.5" stroke-linecap="round"/>'
    '<path d="M41 41 56 56" stroke="url(%23shd)" stroke-width="6" stroke-linecap="round"/>'
    '<circle cx="27" cy="27" r="19" fill="url(%23sgl)" opacity=".93"/>'
    '<circle cx="27" cy="27" r="19" fill="none" stroke="url(%23shd)" stroke-width="4.4"/>'
    '<circle cx="27" cy="27" r="21.4" fill="none" stroke="%233D1568" stroke-width="1.2"/>'
    '<ellipse cx="20" cy="19" rx="7" ry="3.8" fill="%23FFFFFF" opacity=".8" transform="rotate(-32 20 19)"/>'
)

# ── clock ───────────────────────────────────────────────────────────────────
ICONS['clock'] = (
    defs(rad('clf', '#FFFDF3', '#E4D6C2', '36%', '28%', '78%'), lin('clr', '#FFE87A', '#C79A18')) +
    '<circle cx="34" cy="30" r="25" fill="url(%23clr)" stroke="%23A97A00" stroke-width="1.3"/>'
    '<circle cx="34" cy="30" r="20" fill="url(%23clf)" stroke="%23A97A00" stroke-width="1"/>'
    '<path d="M34 14v1.6M50 30h-1.6M34 46v-1.6M18 30h1.6" stroke="%23A97A00" stroke-width="2" stroke-linecap="round"/>'
    '<path d="M34 30V18.5" stroke="%233D1568" stroke-width="3.2" stroke-linecap="round"/>'
    '<path d="M34 30l9.5 5.5" stroke="%233D1568" stroke-width="2.8" stroke-linecap="round"/>'
    '<circle cx="34" cy="30" r="2.4" fill="%233D1568"/>'
    '<ellipse cx="34" cy="58" rx="15" ry="2.6" fill="%23000" opacity=".16"/>'
)

# ── envelope (plain mail; the wax-sealed one is `letter`) ───────────────────
ICONS['mail'] = (
    defs(lin('mlb', '#F3E9FF', '#C39BEF'), lin('mlf', '#FFFFFF', '#E5D4FF')) +
    '<rect x="7" y="15" width="54" height="35" rx="5" fill="url(%23mlb)" stroke="%233D1568" stroke-width="1.5"/>'
    '<path d="M7.6 47.8 26.5 32M60.4 47.8 41.5 32" fill="none" stroke="%23A98AD0" stroke-width="1.8" stroke-linecap="round"/>'
    '<path d="M7.6 17.6 34 37 60.4 17.6" fill="none" stroke="url(%23mlf)" stroke-width="4" stroke-linejoin="round"/>'
    '<path d="M7.6 17.6 34 37 60.4 17.6" fill="none" stroke="%235E2391" stroke-width="1.6" stroke-linejoin="round"/>'
    '<ellipse cx="34" cy="55" rx="18" ry="2.6" fill="%23000" opacity=".16"/>'
)

# ── mobile phone ────────────────────────────────────────────────────────────
ICONS['phone'] = (
    defs(lin('phb', '#6B5A8E', '#241A3D'), lin('phs', '#C6FBF5', '#3FBFB4')) +
    '<rect x="19" y="3" width="30" height="57" rx="6.5" fill="url(%23phb)" stroke="%23140D24" stroke-width="1.5"/>'
    '<rect x="22.6" y="10" width="22.8" height="41" rx="2.6" fill="url(%23phs)"/>'
    '<rect x="30" y="6.2" width="8" height="2" rx="1" fill="%23C4B4E0"/>'
    '<circle cx="34" cy="55.4" r="2.6" fill="%23C4B4E0"/>'
    '<path d="M23.6 11h9L23.6 30z" fill="%23FFFFFF" opacity=".38"/>'
    '<ellipse cx="34" cy="62" rx="13" ry="1.8" fill="%23000" opacity=".16"/>'
)

# ── globe ───────────────────────────────────────────────────────────────────
ICONS['globe'] = (
    defs(rad('gbo', '#8FF3EA', '#0B6C66', '32%', '26%', '80%')) +
    '<circle cx="34" cy="30" r="25" fill="url(%23gbo)" stroke="%23074B47" stroke-width="1.4"/>'
    '<path d="M13 22c5 1.6 7-1 11 .6s3 6 7 6.4 6-3.4 10-2.6 5 4 9 3.4" fill="none" '
    'stroke="%23BFF7C6" stroke-width="5" stroke-linecap="round" opacity=".62"/>'
    '<path d="M20 43c4-2.4 7 .6 11-.4s6-3.4 10-2" fill="none" '
    'stroke="%23BFF7C6" stroke-width="4.4" stroke-linecap="round" opacity=".5"/>'
    '<ellipse cx="34" cy="30" rx="11" ry="25" fill="none" stroke="%23EAFFFD" stroke-width="1.4" opacity=".55"/>'
    '<path d="M9.4 30h49.2M12 19h44M12 41h44" fill="none" stroke="%23EAFFFD" stroke-width="1.4" opacity=".5"/>'
    '<ellipse cx="25" cy="17" rx="8" ry="4.6" fill="%23FFFFFF" opacity=".33" transform="rotate(-28 25 17)"/>'
    '<ellipse cx="34" cy="58" rx="16" ry="2.6" fill="%23000" opacity=".18"/>'
)

# ── hibiscus ────────────────────────────────────────────────────────────────
ICONS['hibiscus'] = (
    defs(rad('hbp', '#FFDDEC', '#CE3F86', '42%', '38%', '76%'),
         rad('hbc', '#FFF6CE', '#DC9C14', '40%', '34%', '72%')) +
    '<g fill="url(%23hbp)" stroke="%23861C57" stroke-width="1.2">'
    '<ellipse cx="34" cy="17" rx="10" ry="13.5"/>'
    '<ellipse cx="34" cy="17" rx="10" ry="13.5" transform="rotate(72 34 30)"/>'
    '<ellipse cx="34" cy="17" rx="10" ry="13.5" transform="rotate(144 34 30)"/>'
    '<ellipse cx="34" cy="17" rx="10" ry="13.5" transform="rotate(216 34 30)"/>'
    '<ellipse cx="34" cy="17" rx="10" ry="13.5" transform="rotate(288 34 30)"/>'
    '</g>'
    '<path d="M34 30 47 47" fill="none" stroke="url(%23hbc)" stroke-width="2.6" stroke-linecap="round"/>'
    '<circle cx="47" cy="47" r="2.6" fill="%23FFE87A"/>'
    '<circle cx="43.5" cy="42" r="1.9" fill="%23FFE87A"/>'
    '<circle cx="34" cy="30" r="6.2" fill="url(%23hbc)" stroke="%23A97A00" stroke-width="1"/>'
)

# ── desert ──────────────────────────────────────────────────────────────────
ICONS['desert'] = (
    defs(rad('dsn', '#FFF7CE', '#FFB33F', '50%', '50%', '62%'),
         lin('dsd', '#F8D79B', '#C98A3C'), lin('dsf', '#FFE9BE', '#E0B274')) +
    '<circle cx="49" cy="17" r="9.5" fill="url(%23dsn)"/>'
    '<path d="M2 42c9-8 16-5 24-1s17 3 40-6v25H2z" fill="url(%23dsd)" stroke="%23A9702C" stroke-width="1.2" stroke-linejoin="round"/>'
    '<path d="M15 50V38a3.2 3.2 0 0 1 6.4 0v12z" fill="%23278F5E" stroke="%2314603D" stroke-width="1.1" stroke-linejoin="round"/>'
    '<path d="M15 43h-3.6a2.6 2.6 0 0 0-2.6 2.6V50M21.4 40h3.4a2.6 2.6 0 0 1 2.6 2.6V47" '
    'fill="none" stroke="%23278F5E" stroke-width="3.6" stroke-linecap="round"/>'
    '<path d="M2 51c12-5 20-1 30 2s22 1 34-4v11H2z" fill="url(%23dsf)"/>'
)

# ── mountain ────────────────────────────────────────────────────────────────
ICONS['mountain'] = (
    defs(lin('mtr', '#95A2CA', '#333D63'), lin('mtb', '#6C79A6', '#232B4B'),
         lin('mts', '#FFFFFF', '#DCE6FF')) +
    '<path d="M2 56 22 20l13 21 5-7 26 22z" fill="url(%23mtb)" stroke="%231A2141" stroke-width="1.3" stroke-linejoin="round"/>'
    '<path d="M22 20 35 41 27 47 2 56z" fill="url(%23mtr)"/>'
    '<path d="M22 20l7.6 12.3-4.6 1.9-3.6-2.6-4 2.8z" fill="url(%23mts)" stroke="%23B9C6E8" stroke-width=".8" stroke-linejoin="round"/>'
    '<path d="M40 34l6.4 5.4-3.8 1.3-2.9-1.6-2.7 1.7z" fill="url(%23mts)" stroke="%23B9C6E8" stroke-width=".8" stroke-linejoin="round"/>'
)

# ── speaker ─────────────────────────────────────────────────────────────────
ICONS['speaker'] = (
    defs(lin('spb', '#C77DFF', '#4B1B7A'), lin('spw', '#7CFFEE', '#00B7A8')) +
    '<path d="M6 24h11L31 11v41L17 40H6z" fill="url(%23spb)" stroke="%232F0F52" stroke-width="1.5" stroke-linejoin="round"/>'
    '<path d="M8 26h7v12H8z" fill="%23FFFFFF" opacity=".25"/>'
    '<path d="M39 22a13.5 13.5 0 0 1 0 20" fill="none" stroke="url(%23spw)" stroke-width="4" stroke-linecap="round"/>'
    '<path d="M48 14a25 25 0 0 1 0 36" fill="none" stroke="url(%23spw)" stroke-width="4" stroke-linecap="round" opacity=".65"/>'
)

# ── ghost ───────────────────────────────────────────────────────────────────
ICONS['ghost'] = (
    defs(lin('ghb', '#FFFFFF', '#C9B8EE'), rad('ghg', '#FFFFFF', '#B9A8E8', '50%', '40%', '66%')) +
    '<circle cx="34" cy="30" r="24" fill="url(%23ghg)" opacity=".28"/>'
    '<path d="M34 5c-10.6 0-19 8.4-19 19v29.6c0 1.7 2 2.5 3.2 1.3l4.4-4.6 4.5 4.8a2 2 0 0 0 2.9 0l4-4.3 4 4.3a2 2 0 0 0 2.9 0l4.5-4.8 4.4 4.6c1.2 1.2 3.2.4 3.2-1.3V24c0-10.6-8.4-19-19-19z" '
    'fill="url(%23ghb)" stroke="%237E6BAE" stroke-width="1.4" stroke-linejoin="round"/>'
    '<ellipse cx="27" cy="25" rx="3.1" ry="4.3" fill="%233A2C63"/>'
    '<ellipse cx="41" cy="25" rx="3.1" ry="4.3" fill="%233A2C63"/>'
    '<ellipse cx="34" cy="36" rx="3.2" ry="4.4" fill="%233A2C63" opacity=".8"/>'
    '<ellipse cx="24" cy="16" rx="6" ry="3.4" fill="%23FFFFFF" opacity=".7" transform="rotate(-26 24 16)"/>'
)

# ── nesting doll (Robert the Doll) ──────────────────────────────────────────
ICONS['doll'] = (
    defs(lin('dlc', '#FFD9E4', '#C43B7E'), rad('dlf', '#FFE3CB', '#C98E63', '38%', '30%', '76%'),
         lin('dla', '#FFFDF0', '#E9D6B4')) +
    '<path d="M34 4c-8.4 0-13.6 7.2-13.6 15.4 0 3.8.9 6.9 2.2 9.1C17 32.9 13.4 40.4 13.4 47.6 13.4 55.6 22.6 60 34 60s20.6-4.4 20.6-12.4c0-7.2-3.6-14.7-9.2-19.1 1.3-2.2 2.2-5.3 2.2-9.1C47.6 11.2 42.4 4 34 4z" '
    'fill="url(%23dlc)" stroke="%23861C57" stroke-width="1.4" stroke-linejoin="round"/>'
    '<path d="M34 34c9.6 0 16.4 5.6 18.6 13.6C50.6 55.6 43 59 34 59s-16.6-3.4-18.6-11.4C17.6 39.6 24.4 34 34 34z" fill="url(%23dla)" opacity=".93"/>'
    '<ellipse cx="34" cy="20" rx="10.2" ry="11" fill="url(%23dlf)" stroke="%238A5A38" stroke-width="1.2"/>'
    '<circle cx="30" cy="19" r="1.7" fill="%233A2C63"/>'
    '<circle cx="38" cy="19" r="1.7" fill="%233A2C63"/>'
    '<path d="M31.4 24.4a3.4 3.4 0 0 0 5.2 0" fill="none" stroke="%23A5563F" stroke-width="1.3" stroke-linecap="round"/>'
    '<circle cx="34" cy="46" r="5" fill="%23F4A6C6"/>'
    '<circle cx="34" cy="46" r="2" fill="%23FFE87A"/>'
)

# ── ticket ──────────────────────────────────────────────────────────────────
ICONS['ticket'] = (
    defs(lin('tkb', '#FFE87A', '#DFA218'), lin('tkg', '#FFFCE6', '#FFE87A')) +
    '<path d="M11 17h30a5 5 0 0 0 10 0h6a4 4 0 0 1 4 4v24a4 4 0 0 1-4 4h-6a5 5 0 0 0-10 0H11a4 4 0 0 1-4-4V21a4 4 0 0 1 4-4z" '
    'fill="url(%23tkb)" stroke="%23A97A00" stroke-width="1.5" stroke-linejoin="round"/>'
    '<path d="M46 22.5v21" stroke="%23A97A00" stroke-width="1.6" stroke-dasharray="3 3.6" stroke-linecap="round"/>'
    '<path d="M11 21h30v10H11z" fill="url(%23tkg)" opacity=".55"/>'
    '<path d="M25 25.5c.9 4.2 2.9 6.8 7.1 7.7-4.2.9-6.2 3.3-7.1 7.5-.9-4.2-2.9-6.6-7.1-7.5 4.2-.9 6.2-3.5 7.1-7.7z" fill="%23FFFDF0"/>'
    '<ellipse cx="34" cy="55" rx="19" ry="2.6" fill="%23000" opacity=".16"/>'
)

# ── t-shirt ─────────────────────────────────────────────────────────────────
ICONS['tshirt'] = (
    defs(lin('tsb', '#C77DFF', '#5E2391'), lin('tsc', '#FFFFFF', '#E3CBFF')) +
    '<path d="M25 7 12 14 5 27l10 5.6 3.4-5.6V55a3 3 0 0 0 3 3h25.2a3 3 0 0 0 3-3V27l3.4 5.6L63 27l-7-13-13-7c-1.8 4.2-5 6.4-9 6.4S26.8 11.2 25 7z" '
    'fill="url(%23tsb)" stroke="%233D1568" stroke-width="1.5" stroke-linejoin="round"/>'
    '<path d="M25 7c1.8 4.2 5 6.4 9 6.4S41.2 11.2 43 7" fill="none" stroke="url(%23tsc)" stroke-width="2.6" stroke-linecap="round"/>'
    '<ellipse cx="24" cy="24" rx="7" ry="4.4" fill="%23FFFFFF" opacity=".3" transform="rotate(-26 24 24)"/>'
)

# ── refresh ─────────────────────────────────────────────────────────────────
_REFRESH_ARM = (
    '<path d="M11 35A23 23 0 0 1 45 15.5" fill="none" stroke="url(%23rfa)" stroke-width="6" stroke-linecap="round"/>'
    '<path d="M38.5 4.5 55 15 36 22.5z" fill="url(%23rfa)"/>'
)
ICONS['refresh'] = (
    defs(lin('rfa', '#7CFFEE', '#0A8F86', '1', '1')) +
    _REFRESH_ARM +
    f'<g transform="rotate(180 34 30)">{_REFRESH_ARM}</g>'
)

# ── comet (distance / remote session) ───────────────────────────────────────
ICONS['comet'] = (
    defs(lin('cmt', '#00E5D4', '#9D4EDD', '1', '1'),
         rad('cmh', '#FFFFFF', '#FFD700', '45%', '40%', '66%')) +
    '<path d="M5 56c12-2.6 20-9 25-19" fill="none" stroke="url(%23cmt)" stroke-width="6" stroke-linecap="round" opacity=".85"/>'
    '<path d="M15 59c9-2 15-6.6 19-13" fill="none" stroke="url(%23cmt)" stroke-width="3.4" stroke-linecap="round" opacity=".5"/>'
    '<path d="M43 6c2.1 9.4 6.1 13.6 15.4 15.4-9.3 2-13.3 6.1-15.4 15.4-2.1-9.4-6.1-13.4-15.4-15.4C36.9 19.4 40.9 15.4 43 6z" fill="url(%23cmh)"/>'
    '<circle cx="24" cy="14" r="2.6" fill="%2300E5D4" opacity=".8"/>'
    '<circle cx="57" cy="42" r="2" fill="%239D4EDD" opacity=".75"/>'
)

# ── cherry blossom ──────────────────────────────────────────────────────────
ICONS['blossom'] = (
    defs(rad('blp', '#FFE8F2', '#EE7FB2', '42%', '36%', '76%'),
         rad('blc', '#FFF6CE', '#DC9C14', '40%', '34%', '72%')) +
    '<g fill="url(%23blp)" stroke="%23B84C82" stroke-width="1.1">'
    '<path d="M34 8c4.6 0 8.4 4.4 8.4 9.8S38.6 28 34 28s-8.4-4.8-8.4-10.2S29.4 8 34 8z"/>'
    '<path d="M34 8c4.6 0 8.4 4.4 8.4 9.8S38.6 28 34 28s-8.4-4.8-8.4-10.2S29.4 8 34 8z" transform="rotate(72 34 30)"/>'
    '<path d="M34 8c4.6 0 8.4 4.4 8.4 9.8S38.6 28 34 28s-8.4-4.8-8.4-10.2S29.4 8 34 8z" transform="rotate(144 34 30)"/>'
    '<path d="M34 8c4.6 0 8.4 4.4 8.4 9.8S38.6 28 34 28s-8.4-4.8-8.4-10.2S29.4 8 34 8z" transform="rotate(216 34 30)"/>'
    '<path d="M34 8c4.6 0 8.4 4.4 8.4 9.8S38.6 28 34 28s-8.4-4.8-8.4-10.2S29.4 8 34 8z" transform="rotate(288 34 30)"/>'
    '</g>'
    '<circle cx="34" cy="30" r="5" fill="url(%23blc)" stroke="%23A97A00" stroke-width=".9"/>'
    '<circle cx="34" cy="30" r="1.8" fill="%23FFFDF0"/>'
)


# ── warning ─────────────────────────────────────────────────────────────────
ICONS['warning'] = (
    defs(lin('wgb', '#FFD75E', '#E08A12')) +
    '<path d="M34 6c1.6 0 3.1.9 3.9 2.3l24 42.2c1.6 2.9-.5 6.5-3.9 6.5H10c-3.4 0-5.5-3.6-3.9-6.5l24-42.2A4.5 4.5 0 0 1 34 6z" '
    'fill="url(%23wgb)" stroke="%23A8630A" stroke-width="1.5" stroke-linejoin="round"/>'
    '<path d="M34 22v16" stroke="%235A3200" stroke-width="5" stroke-linecap="round"/>'
    '<circle cx="34" cy="47.5" r="3.2" fill="%235A3200"/>'
    '<path d="M34 12 15 46" fill="none" stroke="%23FFF3C4" stroke-width="2.4" stroke-linecap="round" opacity=".55"/>'
)

# ── satellite ───────────────────────────────────────────────────────────────
ICONS['satellite'] = (
    defs(lin('stb', '#E2EAFF', '#8296C8'), lin('stp', '#7CC6FF', '#12448C')) +
    '<rect x="3" y="21" width="19" height="17" rx="2" fill="url(%23stp)" stroke="%230D2E63" stroke-width="1.2"/>'
    '<rect x="46" y="21" width="19" height="17" rx="2" fill="url(%23stp)" stroke="%230D2E63" stroke-width="1.2"/>'
    '<path d="M12.5 21v17M3 29.5h19M55.5 21v17M46 29.5h19" stroke="%23BBD8FF" stroke-width="1.1" opacity=".75"/>'
    '<path d="M22 29.5h24" stroke="%23516A9E" stroke-width="3"/>'
    '<rect x="26" y="22" width="16" height="15" rx="3.5" fill="url(%23stb)" stroke="%23425579" stroke-width="1.3"/>'
    '<path d="M34 37v6" stroke="%23425579" stroke-width="2.4"/>'
    '<path d="M34 43c-6 0-10.5 3-10.5 6.5S28 56 34 56s10.5-3 10.5-6.5S40 43 34 43z" '
    'fill="url(%23stb)" stroke="%23425579" stroke-width="1.3"/>'
    '<ellipse cx="34" cy="49.5" rx="4" ry="2.4" fill="%237FA0D8" opacity=".7"/>'
)

# ── trash ───────────────────────────────────────────────────────────────────
ICONS['trash'] = (
    defs(lin('trb', '#D2DBEE', '#6E7C9E')) +
    '<path d="M15 21h38l-2.7 34.4a5 5 0 0 1-5 4.6H22.7a5 5 0 0 1-5-4.6z" '
    'fill="url(%23trb)" stroke="%233C4763" stroke-width="1.5" stroke-linejoin="round"/>'
    '<path d="M26 29v22M34 29v22M42 29v22" stroke="%23FFFFFF" stroke-width="2.4" opacity=".5" stroke-linecap="round"/>'
    '<rect x="11" y="13" width="46" height="8" rx="4" fill="url(%23trb)" stroke="%233C4763" stroke-width="1.4"/>'
    '<path d="M27 9.5h14" stroke="%233C4763" stroke-width="4.4" stroke-linecap="round"/>'
)

# ── jacket ──────────────────────────────────────────────────────────────────
ICONS['jacket'] = (
    defs(lin('jkb', '#93A4DC', '#2B386A'), lin('jkc', '#FFFFFF', '#C9D4F2')) +
    '<path d="M26 5 11 12 6 30l9.5 4.2 3-6V56a3 3 0 0 0 3 3h25a3 3 0 0 0 3-3V28.2l3 6L62 30l-5-18-15-7-8 7.6z" '
    'fill="url(%23jkb)" stroke="%231A2447" stroke-width="1.5" stroke-linejoin="round"/>'
    '<path d="M26 5 34 20.6 42 5" fill="none" stroke="url(%23jkc)" stroke-width="2.8" stroke-linejoin="round"/>'
    '<path d="M34 20.6V56" stroke="%231A2447" stroke-width="1.3" opacity=".6"/>'
    '<circle cx="34" cy="31" r="2.2" fill="%23FFE87A"/>'
    '<circle cx="34" cy="42" r="2.2" fill="%23FFE87A"/>'
)

# ── cap ─────────────────────────────────────────────────────────────────────
ICONS['cap'] = (
    defs(lin('cpb', '#C77DFF', '#5E2391')) +
    '<path d="M34 15c-12.4 0-22 7.4-22 16.6V36h44v-4.4C56 22.4 46.4 15 34 15z" '
    'fill="url(%23cpb)" stroke="%233D1568" stroke-width="1.5" stroke-linejoin="round"/>'
    '<path d="M12 36h34c10.5 0 16 3.1 16 5.8S56.5 46.6 46 46.6H12z" '
    'fill="url(%23cpb)" stroke="%233D1568" stroke-width="1.5" stroke-linejoin="round"/>'
    '<path d="M34 16v20" stroke="%23E7C9FF" stroke-width="1.5" opacity=".6"/>'
    '<circle cx="34" cy="14" r="2.6" fill="%23E0AAFF" stroke="%233D1568" stroke-width="1"/>'
    '<ellipse cx="24" cy="24" rx="7" ry="4" fill="%23FFFFFF" opacity=".26" transform="rotate(-30 24 24)"/>'
)

# ── seated figure (meditation) ──────────────────────────────────────────────
ICONS['meditate'] = (
    defs(rad('mdg', '#FFFFFF', '#00E5D4', '50%', '45%', '62%'),
         lin('mdb', '#C77DFF', '#5E2391'),
         rad('mdf', '#FFE3CB', '#C98E63', '38%', '30%', '76%')) +
    '<circle cx="34" cy="33" r="25" fill="url(%23mdg)" opacity=".28"/>'
    '<path d="M11 50.5c0-4.2 10.3-7 23-7s23 2.8 23 7-10.3 7.5-23 7.5-23-3.3-23-7.5z" '
    'fill="url(%23mdb)" stroke="%233D1568" stroke-width="1.3" stroke-linejoin="round"/>'
    '<path d="M34 23c-7.4 0-12.2 6-13.8 13.6-1 4.8-4.2 7.8-8.2 9.2 2.2 1.6 6.6 1.6 10-.6 '
    '3.2-2.1 5.2-5.2 6.2-8.2 1.4-4 3.4-5.8 5.8-5.8s4.4 1.8 5.8 5.8c1 3 3 6.1 6.2 8.2 '
    '3.4 2.2 7.8 2.2 10 .6-4-1.4-7.2-4.4-8.2-9.2C46.2 29 41.4 23 34 23z" '
    'fill="url(%23mdb)" stroke="%233D1568" stroke-width="1.3" stroke-linejoin="round"/>'
    '<circle cx="34" cy="13.5" r="8.2" fill="url(%23mdf)" stroke="%238A5A38" stroke-width="1.2"/>'
    '<circle cx="34" cy="4.5" r="2.6" fill="%2300FFC8" opacity=".9"/>'
)

# ── star ────────────────────────────────────────────────────────────────────
ICONS['star'] = (
    defs(rad('stg', '#FFFBE0', '#E8A511', '40%', '32%', '74%')) +
    '<circle cx="34" cy="31" r="23" fill="%23FFD700" opacity=".18"/>'
    '<path d="M34 5 41.8 22.6 61 24.8 46.6 37.6 50.6 56.4 34 46.8 17.4 56.4 21.4 37.6 7 24.8 26.2 22.6z" '
    'fill="url(%23stg)" stroke="%23A97A00" stroke-width="1.3" stroke-linejoin="round"/>'
    '<path d="M34 12.6 39.2 24.8 52.4 26.4 42.6 35.2" fill="none" stroke="%23FFFDF0" '
    'stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" opacity=".8"/>'
)


def moon_phase(lit, waxing):
    """Draw one lunar phase.

    `lit` is the illuminated fraction (0 new .. 1 full). Built from a half-disc
    plus a terminator ellipse, all clipped to the moon — an earlier version
    drew the limb and terminator as two arcs, but the sweep flags did not
    behave as expected and quarters came out mirrored, so this composes only
    rectangles and ellipses, where the result is unambiguous.
    """
    DARK, LIT = '%232A2247', 'url(%23mpg)'
    head = ('<defs>' + rad('mpg', '#FFF6D0', '#D9A63C', '40%', '30%', '78%') +
            '<clipPath id="mpc"><circle cx="34" cy="30" r="25"/></clipPath></defs>')
    rim = ('<circle cx="34" cy="30" r="25" fill="none" stroke="%23A97A00" '
           'stroke-width="1.3"/>')

    def craters(on_right):
        xs = [(41, 20, 3.4), (46, 35, 2.4), (37, 43, 1.8)]
        if not on_right:
            xs = [(68 - x, y, r) for x, y, r in xs]
        return ''.join(f'<circle cx="{x}" cy="{y}" r="{r}" fill="%23D9A63C" '
                       f'opacity=".38"/>' for x, y, r in xs)

    if lit <= 0.01:
        return head + f'<circle cx="34" cy="30" r="25" fill="{DARK}"/>' + rim
    if lit >= 0.99:
        return (head + f'<circle cx="34" cy="30" r="25" fill="{LIT}"/>' +
                craters(True) + rim)

    # lit half-disc on the leading limb: right while waxing, left while waning
    half_x = 34 if waxing else 9
    half = f'<rect x="{half_x}" y="5" width="25" height="50" fill="{LIT}"/>'
    # terminator: eats into the half for a crescent, spills past it for a gibbous
    rx = 25 * abs(1 - 2 * lit)
    term = (f'<ellipse cx="34" cy="30" rx="{rx:.1f}" ry="25" '
            f'fill="{DARK if lit < 0.5 else LIT}"/>')

    return (head +
            f'<g clip-path="url(%23mpc)">'
            f'<circle cx="34" cy="30" r="25" fill="{DARK}"/>{half}{term}'
            + (craters(waxing) if lit >= 0.5 else '') +
            '</g>' + rim)


for _key, _lit, _wax in [('new', 0.0, True), ('waxing-crescent', 0.25, True),
                         ('first-quarter', 0.5, True), ('waxing-gibbous', 0.75, True),
                         ('full', 1.0, True), ('waning-gibbous', 0.75, False),
                         ('last-quarter', 0.5, False), ('waning-crescent', 0.25, False)]:
    ICONS[f'moon-{_key}'] = moon_phase(_lit, _wax)


# ── cloud ───────────────────────────────────────────────────────────────────
ICONS['cloud'] = (
    defs(lin('cdb', '#FFFFFF', '#C3D2F0')) +
    '<path d="M14 50A12 12 0 0 1 14 26A15 15 0 0 1 42 20A17 17 0 0 1 54 50Z" '
    'fill="url(%23cdb)" stroke="%237E93BF" stroke-width="1.4" stroke-linejoin="round"/>'
    '<ellipse cx="24" cy="30" rx="8" ry="4.4" fill="%23FFFFFF" opacity=".7" transform="rotate(-22 24 30)"/>'
)

# ── fountain pen ────────────────────────────────────────────────────────────
ICONS['pen'] = (
    defs(lin('pnb', '#C77DFF', '#5E2391'), lin('pnn', '#FFE87A', '#C79A18')) +
    '<path d="M10 57h48" stroke="%2300E5D4" stroke-width="3.4" stroke-linecap="round" opacity=".7"/>'
    '<path d="M50 6 62 18 32 46 20 50 24 38z" fill="url(%23pnb)" stroke="%233D1568" stroke-width="1.5" stroke-linejoin="round"/>'
    '<path d="M20 50 24 38 32 46z" fill="url(%23pnn)" stroke="%23A97A00" stroke-width="1.2" stroke-linejoin="round"/>'
    '<path d="M46 10 58 22" stroke="%23E7C9FF" stroke-width="2.6" stroke-linecap="round" opacity=".7"/>'
    '<circle cx="20.6" cy="49.4" r="1.8" fill="%233D1568"/>'
)


def _gear(teeth=8, r_out=28, r_in=21.5, hole=8.5, cx=34, cy=30):
    """Cog outline: four points per tooth so the tips come out flat, plus an
    even-odd hole so the centre reads as a bore rather than a dot."""
    import math
    T = 2 * math.pi / teeth
    w, g = T * 0.19, T * 0.11
    pts = []
    for i in range(teeth):
        a = i * T - math.pi / 2
        for r, ang in ((r_out, a - w), (r_out, a + w),
                       (r_in, a + w + g), (r_in, a + T - w - g)):
            pts.append(f'{cx + r * math.cos(ang):.1f} {cy + r * math.sin(ang):.1f}')
    ring = (f'M{cx - hole} {cy}'
            f'a{hole} {hole} 0 1 0 {hole * 2} 0'
            f'a{hole} {hole} 0 1 0 {-hole * 2} 0z')
    return 'M' + 'L'.join(pts) + 'z' + ring


ICONS['gear'] = (
    defs(lin('grb', '#D8E2FA', '#5F6E97')) +
    f'<path d="{_gear()}" fill-rule="evenodd" fill="url(%23grb)" '
    'stroke="%23333E5E" stroke-width="1.4" stroke-linejoin="round"/>'
)


# ── Social marks ────────────────────────────────────────────────────────────
# These replace Font Awesome, which was pulling a render-blocking CDN
# stylesheet plus two woff2 files (~370 KB) to draw six glyphs. They render
# through `mask-image` rather than `background-image`, so a single shape
# inherits `currentColor` and follows the link's hover state instead of
# needing one file per colour.
#
# Each is a simplified single-path version of the platform's own mark, used
# to link to that platform — which is what their brand guidelines are for.
SOCIAL = {}

SOCIAL['instagram'] = (
    '<path fill-rule="evenodd" d="M7 2h10a5 5 0 0 1 5 5v10a5 5 0 0 1-5 5H7a5 5 0 0 1-5-5V7a5 5 0 0 1 5-5z'
    'm0 2a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h10a3 3 0 0 0 3-3V7a3 3 0 0 0-3-3z'
    'm5 3.4a4.6 4.6 0 1 1 0 9.2 4.6 4.6 0 0 1 0-9.2z'
    'm0 2a2.6 2.6 0 1 0 0 5.2 2.6 2.6 0 0 0 0-5.2z'
    'M17.6 5.9a1.25 1.25 0 1 1 0 2.5 1.25 1.25 0 0 1 0-2.5z"/>'
)

SOCIAL['facebook'] = (
    '<path d="M22 12a10 10 0 1 0-11.56 9.88v-6.99H7.9V12h2.54V9.8c0-2.51 1.49-3.9 3.77-3.9 1.09 0 2.24.2 2.24.2v2.46h-1.26c-1.24 0-1.63.77-1.63 1.56V12h2.78l-.45 2.89h-2.33v6.99A10 10 0 0 0 22 12z"/>'
)

SOCIAL['tiktok'] = (
    '<path d="M16.6 5.82A4.28 4.28 0 0 1 15.54 3h-3.09v12.4a2.59 2.59 0 1 1-1.82-2.47V9.8a5.72 5.72 0 1 0 4.91 5.66V9.01a7.35 7.35 0 0 0 4.3 1.38V7.3a4.29 4.29 0 0 1-3.24-1.48z"/>'
)

SOCIAL['youtube'] = (
    '<path fill-rule="evenodd" d="M23 12c0-3.2-.41-4.74-.41-4.74a3.02 3.02 0 0 0-2.12-2.13C18.93 4.72 12 4.72 12 4.72s-6.93 0-8.47.41A3.02 3.02 0 0 0 1.41 7.26C1 8.8 1 12 1 12s0 3.2.41 4.74a3.02 3.02 0 0 0 2.12 2.13c1.54.41 8.47.41 8.47.41s6.93 0 8.47-.41a3.02 3.02 0 0 0 2.12-2.13C23 15.2 23 12 23 12z'
    'M9.75 15.27V8.73L15.5 12z"/>'
)

SOCIAL['spotify'] = (
    '<path d="M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20zm4.59 14.42a.62.62 0 0 1-.86.21c-2.35-1.44-5.3-1.76-8.79-.96a.62.62 0 1 1-.28-1.22c3.81-.87 7.08-.5 9.72 1.11.29.18.39.58.21.86zm1.22-2.72a.78.78 0 0 1-1.07.26c-2.69-1.65-6.79-2.13-9.97-1.17a.78.78 0 1 1-.45-1.49c3.63-1.1 8.15-.56 11.24 1.33.37.23.48.71.25 1.07zm.11-2.84c-3.23-1.92-8.55-2.09-11.63-1.16a.93.93 0 1 1-.54-1.79c3.54-1.07 9.42-.87 13.13 1.34a.93.93 0 1 1-.96 1.6z"/>'
)

SOCIAL['star'] = (
    '<path d="M12 2.6l2.95 6.16 6.55.86-4.8 4.6 1.22 6.65L12 17.66 6.08 20.87l1.22-6.65-4.8-4.6 6.55-.86z"/>'
)

SOCIAL_TEMPLATE = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">{body}</svg>'

TEMPLATE = ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 68 64">{body}</svg>')


def to_url(body):
    """Percent-encode the whole SVG.

    An earlier version kept `"` and `#` in the `safe` set, which meant the first
    attribute quote inside the SVG terminated the CSS string and every rule after
    it was dropped. Nothing is safe here except the percent signs already written
    into the markup as %23.
    """
    svg = TEMPLATE.format(body=body)
    return 'url("data:image/svg+xml,' + quote(svg, safe='%') + '")'


def build_css():
    """Bind each icon to its rendered file, once, as a custom property.

    The bodies above are no longer emitted as data URIs — they are the geometry
    that tools/build_photoreal_icons.py renders with a real lighting rig, and
    the result ships as WebP from images/icons/. Going through `--pico-*` still
    means anything can reuse an icon without repeating the URL, which matters
    for `::before` on elements whose label is set with textContent.
    """
    import glob as _glob
    import os as _os

    rendered = sorted(_os.path.basename(f)[:-5]
                      for f in _glob.glob(_os.path.join(HERE, '..', 'images', 'icons', '*.webp')))
    photoreal = {'orb': '../images/icon-orb.webp', 'eye': '../images/icon-eye.webp'}

    lines = [START, ':root {']
    for name, path in photoreal.items():
        lines.append(f"  --pico-{name}: url('{path}');")
    for name in rendered:
        lines.append(f"  --pico-{name}: url('../images/icons/{name}.webp');")
    lines += ['}',
              '.pico {',
              '  display: inline-block;',
              '  width: 1.15em;',
              '  height: 1.15em;',
              '  vertical-align: -0.2em;',
              '  background-repeat: no-repeat;',
              '  background-position: center;',
              '  background-size: contain;',
              '  flex-shrink: 0;',
              '  filter: drop-shadow(0 2px 5px rgba(0, 0, 0, 0.35));',
              '  transform-origin: center center;',
              '  transition: transform 0.28s cubic-bezier(0.34, 1.56, 0.64, 1), filter 0.28s ease;',
              '}']
    for name in list(photoreal) + rendered:
        lines.append(f'.pico--{name} {{ background-image: var(--pico-{name}); }}')

    lines += [
        '/* ── Living Animations for Photorealistic Icons ── */',
        '@keyframes picoSparkle {',
        '  0%, 100% { transform: scale(1) rotate(0deg); filter: brightness(1) drop-shadow(0 0 3px rgba(0, 229, 212, 0.45)); }',
        '  50% { transform: scale(1.12) rotate(6deg); filter: brightness(1.28) drop-shadow(0 0 8px rgba(0, 255, 200, 0.85)); }',
        '}',
        '.pico--sparkle, .pico--star, .pico--comet { animation: picoSparkle 3.2s ease-in-out infinite; }',
        '',
        '@keyframes picoCandle {',
        '  0%, 100% { transform: scale(1) rotate(0deg); filter: brightness(1) drop-shadow(0 0 3px rgba(255, 215, 0, 0.4)); }',
        '  25% { transform: scale(1.05) rotate(-2.5deg); filter: brightness(1.22) drop-shadow(0 0 9px rgba(255, 215, 0, 0.85)); }',
        '  75% { transform: scale(0.97) rotate(2deg); filter: brightness(1.12) drop-shadow(0 0 6px rgba(255, 180, 0, 0.65)); }',
        '}',
        '.pico--candle { animation: picoCandle 2.2s ease-in-out infinite; transform-origin: center bottom; }',
        '',
        '@keyframes picoBell {',
        '  0%, 100% { transform: rotate(0deg); }',
        '  20% { transform: rotate(-7deg); }',
        '  40% { transform: rotate(6deg); }',
        '  60% { transform: rotate(-4deg); }',
        '  80% { transform: rotate(2deg); }',
        '}',
        '.pico--bell { animation: picoBell 4.8s ease-in-out infinite; transform-origin: top center; }',
        '',
        '@keyframes picoOrbPulse {',
        '  0%, 100% { transform: scale(1); filter: brightness(1) drop-shadow(0 0 4px rgba(157, 78, 221, 0.5)); }',
        '  50% { transform: scale(1.09); filter: brightness(1.24) drop-shadow(0 0 10px rgba(0, 229, 212, 0.85)); }',
        '}',
        '.pico--orb, .pico--eye { animation: picoOrbPulse 3.6s ease-in-out infinite; }',
        '',
        '@keyframes picoGhostFloat {',
        '  0%, 100% { transform: translateY(0) scale(1); opacity: 0.92; }',
        '  50% { transform: translateY(-3.5px) scale(1.05); opacity: 1; filter: drop-shadow(0 0 8px rgba(200, 180, 255, 0.8)); }',
        '}',
        '.pico--ghost { animation: picoGhostFloat 3s ease-in-out infinite; }',
        '',
        '@keyframes picoDoveFloat {',
        '  0%, 100% { transform: translateY(0) rotate(0deg); }',
        '  50% { transform: translateY(-2.5px) rotate(-3deg); }',
        '}',
        '.pico--dove { animation: picoDoveFloat 3.6s ease-in-out infinite; }',
        '',
        '@keyframes picoPranicBreath {',
        '  0%, 100% { transform: scale(1); }',
        '  50% { transform: scale(1.07); filter: brightness(1.15) drop-shadow(0 0 6px rgba(0, 255, 200, 0.5)); }',
        '}',
        '.pico--leaf, .pico--blossom, .pico--hibiscus, .pico--meditate { animation: picoPranicBreath 4s ease-in-out infinite; }',
        '',
        '@keyframes picoMoonGlow {',
        '  0%, 100% { filter: brightness(1) drop-shadow(0 0 3px rgba(255, 215, 0, 0.35)); }',
        '  50% { filter: brightness(1.2) drop-shadow(0 0 9px rgba(0, 229, 212, 0.75)); }',
        '}',
        '.pico--moon, .pico--moon-full, .pico--moon-new, .pico--moon-first-quarter,',
        '.pico--moon-last-quarter, .pico--moon-waxing-crescent, .pico--moon-waxing-gibbous,',
        '.pico--moon-waning-crescent, .pico--moon-waning-gibbous {',
        '  animation: picoMoonGlow 4.2s ease-in-out infinite;',
        '}',
        '',
        '@keyframes picoBagHop {',
        '  0%, 82%, 100% { transform: scale(1) translateY(0); }',
        '  88% { transform: scale(1.09, 0.91) translateY(-2.5px); }',
        '  94% { transform: scale(0.95, 1.05) translateY(-3.5px); }',
        '}',
        '.pico--bag { animation: picoBagHop 4.6s ease-in-out infinite; }',
        '',
        '@keyframes picoGearSpin {',
        '  0% { transform: rotate(0deg); }',
        '  100% { transform: rotate(360deg); }',
        '}',
        '.pico--gear { animation: picoGearSpin 22s linear infinite; }',
        '',
        '/* social marks — masks, so they take currentColor */',
        '.sico {',
        '  display: inline-block;',
        '  width: 1em;',
        '  height: 1em;',
        '  vertical-align: -0.13em;',
        '  background-color: currentColor;',
        '  -webkit-mask-repeat: no-repeat;',
        '          mask-repeat: no-repeat;',
        '  -webkit-mask-position: center;',
        '          mask-position: center;',
        '  -webkit-mask-size: contain;',
        '          mask-size: contain;',
        '  flex-shrink: 0;',
        '}']
    for name, body in SOCIAL.items():
        url = ('url("data:image/svg+xml,' +
               quote(SOCIAL_TEMPLATE.format(body=body), safe='%') + '")')
        lines.append(f'.sico--{name} {{ -webkit-mask-image: {url}; mask-image: {url}; }}')

    lines.append(END)
    return '\n'.join(lines) + '\n'


def main():
    css = open(CSS, encoding='utf-8').read()
    block = build_css()
    if START in css:
        css = re.sub(re.escape(START) + r'.*?' + re.escape(END) + r'\n?',
                     block, css, flags=re.S)
    else:
        css = css.rstrip() + '\n\n' + block
    open(CSS, 'w', encoding='utf-8').write(css)
    import glob as _g, os as _o
    n = len(_g.glob(_o.path.join(HERE, '..', 'images', 'icons', '*.webp')))
    print(f'  bound {n} rendered icons + 2 photoreal cut-outs + {len(SOCIAL)} social masks')


if __name__ == '__main__':
    print('Building pico icon CSS...')
    main()
