#!/usr/bin/env python3
"""Write the canonical / Open Graph / Twitter / JSON-LD block into every page.

Before this, index.html had three og: tags and no og:image, the six subpages
had none at all, and nothing had a canonical link or structured data. Shared
anywhere — iMessage, WhatsApp, Facebook, Slack — the site rendered as a bare
URL with no picture.

Everything is written between markers so this is re-runnable, and the domain
lives in one constant. If the site ships somewhere other than SITE, change it
here and re-run rather than editing seven files.

Deliberately absent from the structured data:
  * telephone — the published number is a 555 placeholder, and structured data
    is exactly what search engines lift into a result card.
  * sameAs — the social links all point at bare platform roots
    (https://instagram.com), not at profiles, so there is nothing to assert.
Add both here once the real values exist.

Run:  python3 tools/build_meta.py
"""
import glob
import io
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..')

SITE = 'https://bethelisepsychic.com'
NAME = 'Beth Elise Psychic Medium'
EMAIL = 'hello@bethelisepsychic.com'
CARD = f'{SITE}/images/og-card.jpg'

START = '  <!-- ===== META: generated by tools/build_meta.py — do not edit ===== -->'
END = '  <!-- ===== END META ===== -->'

# og:description per page, kept shorter and warmer than the SEO description
BLURBS = {
    'index.html': 'Step into the light. Psychic readings, Reiki healing and EFT Tapping '
                  'with certified practitioner Beth Elise.',
    'pages/about.html': 'Meet Beth Elise — evidential psychic medium, Reiki practitioner '
                        'and certified Tapping Solution guide.',
    'pages/contact.html': 'Book a reading, a Reiki session or a Tapping session with '
                          'Beth Elise — in New Jersey or virtually worldwide.',
    'pages/merch.html': 'Wear your light. Sacred tees, hoodies and talismans from the '
                        'Beth Elise collection.',
    'pages/notes-by-beth.html': 'A handwritten, channeled letter for your soul — sealed '
                                'and sent to you by Beth Elise.',
    'pages/services.html': 'Evidential mediumship, restorative Reiki energy healing and '
                           'somatic EFT Tapping.',
    'pages/testimonials.html': 'What clients say about their readings, healing sessions '
                               'and soul letters with Beth Elise.',
    'pages/privacy.html': 'How Beth Elise handles the information you send through '
                          'this website. No trackers, nothing sold or shared.',
    'pages/terms.html': 'Terms for booking sessions and ordering, including the nature '
                        'and limits of the services offered.',
}


def canonical_for(rel):
    return f'{SITE}/' if rel == 'index.html' else f'{SITE}/{rel}'


def schema():
    """One graph on the homepage: who she is, and what she offers."""
    services = [
        ('Psychic Reading',
         'Evidential mediumship connecting you with loved ones in spirit.'),
        ('Reiki Healing',
         'Usui Reiki energy work to clear and rebalance the chakra system.'),
        ('EFT Tapping',
         'Somatic acupressure tapping with a certified Tapping Solution practitioner.'),
    ]
    return {
        '@context': 'https://schema.org',
        '@graph': [
            {
                '@type': 'ProfessionalService',
                '@id': f'{SITE}/#business',
                'name': NAME,
                'url': SITE,
                'image': CARD,
                'email': EMAIL,
                'description': BLURBS['index.html'],
                'priceRange': '$$',
                'address': {
                    '@type': 'PostalAddress',
                    'addressRegion': 'NJ',
                    'addressCountry': 'US',
                },
                'areaServed': [
                    {'@type': 'State', 'name': 'New Jersey'},
                    {'@type': 'Place', 'name': 'Worldwide (virtual sessions)'},
                ],
                'openingHoursSpecification': [{
                    '@type': 'OpeningHoursSpecification',
                    'dayOfWeek': ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
                    'opens': '10:00',
                    'closes': '18:00',
                }],
                'founder': {'@id': f'{SITE}/#beth'},
                'hasOfferCatalog': {
                    '@type': 'OfferCatalog',
                    'name': 'Sessions & Healing Modalities',
                    'itemListElement': [{
                        '@type': 'Offer',
                        'itemOffered': {'@type': 'Service', 'name': n, 'description': d},
                    } for n, d in services],
                },
            },
            {
                '@type': 'Person',
                '@id': f'{SITE}/#beth',
                'name': 'Beth Elise',
                'jobTitle': 'Psychic Medium, Reiki Practitioner & Certified Tapping Practitioner',
                'url': f'{SITE}/pages/about.html',
                'worksFor': {'@id': f'{SITE}/#business'},
            },
        ],
    }


def block(rel, title, desc):
    up = '../' if rel.startswith('pages/') else ''
    lines = [
        START,
        f'  <link rel="canonical" href="{canonical_for(rel)}" />',
        f'  <meta property="og:site_name" content="{NAME}" />',
        '  <meta property="og:type" content="website" />',
        '  <meta property="og:locale" content="en_US" />',
        f'  <meta property="og:url" content="{canonical_for(rel)}" />',
        f'  <meta property="og:title" content="{title}" />',
        f'  <meta property="og:description" content="{desc}" />',
        f'  <meta property="og:image" content="{CARD}" />',
        '  <meta property="og:image:width" content="1200" />',
        '  <meta property="og:image:height" content="630" />',
        '  <meta property="og:image:alt" content="The Beth Elise Psychic Medium wordmark '
        'over a moonlit enchanted forest" />',
        '  <meta name="twitter:card" content="summary_large_image" />',
        f'  <meta name="twitter:title" content="{title}" />',
        f'  <meta name="twitter:description" content="{desc}" />',
        f'  <meta name="twitter:image" content="{CARD}" />',
        # PNG, not WebP: some browsers ignore a WebP favicon outright
        f'  <link rel="icon" href="{up}images/favicon-32.png" sizes="32x32" type="image/png" />',
        f'  <link rel="icon" href="{up}images/favicon-192.png" sizes="192x192" type="image/png" />',
        f'  <link rel="apple-touch-icon" href="{up}images/favicon-180.png" />',
        f'  <link rel="manifest" href="{up}site.webmanifest" />',
    ]
    if rel == 'index.html':
        lines.append('  <script type="application/ld+json">')
        lines.append(json.dumps(schema(), indent=2))
        lines.append('  </script>')
    lines.append(END)
    return '\n'.join(lines) + '\n'


def main():
    pages = ['index.html'] + sorted(
        os.path.relpath(p, ROOT) for p in glob.glob(os.path.join(ROOT, 'pages', '*.html')))
    for rel in pages:
        path = os.path.join(ROOT, rel)
        s = io.open(path, encoding='utf-8').read()

        title = re.search(r'<title>(.*?)</title>', s, re.S).group(1).strip()
        desc = BLURBS.get(rel) or re.search(
            r'<meta name="description" content="(.*?)"', s, re.S).group(1).strip()

        # clear anything this script or the original author left behind
        s = re.sub(re.escape(START) + r'.*?' + re.escape(END) + r'\n?', '', s, flags=re.S)
        s = re.sub(r'[ \t]*<meta property="og:[^>]*>\n?', '', s)
        s = re.sub(r'[ \t]*<meta name="twitter:[^>]*>\n?', '', s)
        s = re.sub(r'[ \t]*<link rel="canonical"[^>]*>\n?', '', s)

        s = s.replace('</head>', block(rel, title, desc) + '</head>', 1)
        io.open(path, 'w', encoding='utf-8').write(s)
        print(f'  {rel}')

    print(f'\n  {len(pages)} pages: canonical + Open Graph + Twitter card, '
          f'JSON-LD on the homepage')


if __name__ == '__main__':
    print('Building meta...')
    main()
